import React from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="es">
      <body>
        <nav>
          {/* Puedes agregar enlaces de navegación aquí */}
         
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
